### PR TITLE
Update 0628.py

### PR DESCRIPTION
**Pull request by ankurbhambri**
image

The easiest way to solve this problem is using indexing and maximum from the front and rear indexing after sorting.

### CODE REVIEW

**Comment by javadev** [comment]
The existed sollution is faster

image

**Comment by ankurbhambri** [comment]
@javadev Leetcode calculations vary all the time but existed solution is hard to understand. You can refer to the below screenshot it seems a balanced solution.

image

**Comment by javadev** [comment]
👍

**Comment by javadev** [comment]
98% :)

image

**Comment by ankurbhambri** [comment]
But at the same time, it's not memory efficient.

**Pull request closed without merging**
